

class FeedbackStates:
    FEEDBACK_STATE_GET = 200
    FEEDBACK_STATE_CHECK = 201
    FEEDBACK_STATE_MAKE_FEEDBACK = 202
    FEEDBACK_STATE_LOOK = 203
    FEEDBACK_STATE_MODERATION = 204
    FEEBACK_EDIT_FEEDBACK = 205