

class OrderStates:
    ORDER_STATE_GET_LOCATION = 500
    ORDER_STATE_GET_DATETIME = 501
    ORDER_STATE_GET_OTHER_INFO = 502
    ORDER_STATE_IS_CORRECT = 503
    ORDER_STATE_GET_POINT_TO_CHANGE = 504
    
